---
- name: Testing andrewrothstein.gator
  hosts: all
  roles:
    - role: '{{ playbook_dir }}'
  tasks:
    - name: Executing 'gator --version'
      ansible.builtin.command: /usr/local/bin/gator --version
      changed_when: false
      register: gator_test_output
    - name: Output of 'gator --version'
      ansible.builtin.debug:
        msg: '{{ gator_test_output.stdout }}'
