---
- hosts: all
  roles:
  - role: '{{ playbook_dir }}'
  tasks:
  - command: /usr/local/bin/gator --version
    register: gator_test_output
  - name: gator --version
    debug:
      msg: '{{ gator_test_output.stdout }}'
